version: "3.9"

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana
  prometheus:
    image: bitnami/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
      - prom-conf:/etc/prometheus
  alertmanager:
    image: bitnami/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - alertmanager-conf:/opt/bitnami/alertmanager/conf
  apache:
    image: httpd
    ports:
      - '80:80'
    volumes:
      - website:/usr/local/apache2
  node-exporter:
    image: bitnami/node-exporter
    ports:
      - "9100:9100"    
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
volumes:
    grafana-data:
    grafana-conf:
    prom-data:
    prom-conf:
    alertmanager-conf:
    website:
